### ISSUE TITLE
API script catch statement

### ISSUE THREAD

**Issue by ehsaan-israr** [brendandahl/pdf.js.utils#3]
i download PDF.js  from https://mozilla.github.io/pdf.js/getting_started/#download
i copy two files pdf.js and pdf.worker.js in my project and when i open it gives an error on

 if (typeof globalScope.Promise.prototype.catch !== 'function')

if i comment out that block then blow code is going to indicate error

![image](https://cloud.githubusercontent.com/assets/11690482/12064616/77c132aa-afe9-11e5-93dd-f8b7c415ded9.png)

**Comment by brendandahl** [comment]
Please file an issue at https://github.com/mozilla/pdf.js . This repo is for utilities that I've made.
